const $=s=>document.querySelector(s),money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(d.error||'Request failed'),{status:r.status});return d}
let products=[],orders=[];
async function load(){try{const me=await api('/api/me');if(!me.user||me.user.role!=='admin'){adminStatus.innerHTML='Admin login required. Create the first admin in <a href="admin_setup.html">Admin Setup</a>, or login with that admin account from <a href="account.html">My Account</a>.';document.querySelectorAll('form,table').forEach(x=>x.style.opacity='.4');return}adminStatus.textContent=`Logged in as ${me.user.name} (${me.user.email})`;products=await api('/api/admin/products');orders=await api('/api/admin/orders');renderProducts();renderOrders();renderBeautyDashboard();sProducts.textContent=products.filter(p=>p.active!==false).length;sStock.textContent=products.reduce((s,p)=>s+Number(p.stock),0);sOrders.textContent=orders.length;sRevenue.textContent=money(orders.filter(o=>o.payment_status==='paid'||o.payment_method==='Cash on Delivery').reduce((s,o)=>s+Number(o.total),0))}catch(e){adminStatus.textContent=e.message}}
function renderProducts(){productRows.innerHTML=products.map(p=>`<tr><td>${p.emoji} <b>${p.name}</b><br><small>${p.category}</small></td><td>${money(p.price)}</td><td>${p.stock}</td><td>${p.active?'Active':'Hidden'}</td><td class="admin-actions"><button onclick="editP(${p.id})">Edit</button><button onclick="toggleP(${p.id})">${p.active?'Hide':'Show'}</button><button onclick="delP(${p.id})">Delete</button></td></tr>`).join('')}
function renderBeautyDashboard(){const categories=['Skincare','Makeup','Hair Care','Fragrance','Beauty Essentials'];const counts=categories.map(c=>({name:c,count:products.filter(p=>String(p.category).toLowerCase()===c.toLowerCase()).length}));const max=Math.max(1,...counts.map(x=>x.count));const snap=document.querySelector('#categorySnapshot');if(snap)snap.innerHTML=counts.map(x=>`<div class="category-snapshot-row"><b>${x.name}</b><div class="category-snapshot-track"><div class="category-snapshot-fill" style="width:${Math.max(8,Math.round(x.count/max*100))}%"></div></div><span>${x.count}</span></div>`).join('');const low=products.filter(p=>Number(p.stock)<=10).sort((a,b)=>Number(a.stock)-Number(b.stock)).slice(0,6);const box=document.querySelector('#lowStock');if(box)box.innerHTML=low.length?low.map(p=>`<div class="low-stock-item"><div><b>${p.emoji||'✨'} ${p.name}</b><small>${p.category}</small></div><em>${p.stock} left</em></div>`).join(''):'<p class="admin-empty">All products have healthy stock levels ✨</p>'}
function renderOrders(){const statuses=['Payment pending','Order confirmed','Processing','Packed','Shipped','Delivered','Cancelled'];orderRows.innerHTML=orders.length?orders.slice(0,30).map(o=>`<div class="admin-order-card"><div><b>${o.order_no}</b> — ${o.customer_name}<br><small>${o.customer_email} • ${o.payment_method} • ${o.payment_status}</small><div class="tracking-edit"><input id="courier-${o.id}" placeholder="Courier e.g. Shiprocket" value="${o.shipping_courier||''}"><input id="track-${o.id}" placeholder="Tracking number" value="${o.tracking_number||''}"><input id="url-${o.id}" placeholder="Tracking URL (optional)" value="${o.tracking_url||''}"></div></div><div><b>${money(o.total)}</b><select id="status-${o.id}">${statuses.map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select><button onclick="saveOrder(${o.id})">Save</button></div></div>`).join(''):'<p class="muted">No database orders yet.</p>'}
async function saveOrder(id){const status=document.querySelector('#status-'+id).value;const shipping_courier=document.querySelector('#courier-'+id).value.trim();const tracking_number=document.querySelector('#track-'+id).value.trim();const tracking_url=document.querySelector('#url-'+id).value.trim();try{await api('/api/admin/orders/'+id,{method:'PUT',body:JSON.stringify({status,shipping_courier,tracking_number,tracking_url})});await load()}catch(x){alert(x.message);load()}}
addProduct.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));['price','mrp','stock'].forEach(k=>d[k]=Number(d[k]));try{await api('/api/admin/products',{method:'POST',body:JSON.stringify(d)});e.target.reset();load()}catch(x){alert(x.message)}};
async function editP(id){const p=products.find(x=>x.id===id);const name=prompt('Product name',p.name);if(name===null)return;const price=Number(prompt('Price',p.price));const stock=Number(prompt('Stock',p.stock));if(!Number.isFinite(price)||!Number.isFinite(stock))return;await api('/api/admin/products/'+id,{method:'PUT',body:JSON.stringify({...p,name,price,stock})});load()}
async function toggleP(id){const p=products.find(x=>x.id===id);await api('/api/admin/products/'+id,{method:'PUT',body:JSON.stringify({...p,active:!p.active})});load()}
async function delP(id){if(!confirm('Delete this product from the database?'))return;try{await api('/api/admin/products/'+id,{method:'DELETE'});load()}catch(x){alert(x.message)}}
load();