const $=s=>document.querySelector(s),money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(d.error||'Request failed'),{status:r.status});return d}
let products=[],orders=[];
const cats=[['Skincare','💧','Healthy Skin, Happier You'],['Makeup','💄','Express Your Beauty'],['Hair Care','〰','Stronger Hair, Brighter You'],['Fragrance','🌸','Scents That Stay With You'],['Beauty Essentials','🛍','Everyday Beauty Must-Haves']];
function sprite(p,cls='lux-product-img'){const id=Number(p?.id);return id>=1&&id<=12?`<span class="${cls} product-sprite product-sprite-${id}"></span>`:`<span class="${cls} lux-emoji">${p?.emoji||'✨'}</span>`}
function renderVisuals(){
  const croot=$('#collections');if(croot)croot.innerHTML=cats.map(([cat,icon,tag])=>{const list=products.filter(p=>p.category===cat&&p.active!==false);const p=list[0];return `<a class="lux-category-card" href="shop.html?category=${encodeURIComponent(cat)}"><div class="lux-cat-copy"><span>${icon}</span><h3>${cat==='Beauty Essentials'?'Essentials':cat}</h3><p>${tag}</p><b>${list.length} PRODUCTS →</b></div>${p?sprite(p,'lux-cat-image'):''}</a>`}).join('');
  const featured=$('#featuredAdminProducts');if(featured)featured.innerHTML=products.slice(0,3).map(p=>`<a href="product.html?id=${p.id}" class="lux-feature-card">${sprite(p)}<div><b>${p.name}</b><small>${p.category}</small></div></a>`).join('');
  const fresh=$('#newAdminProducts');if(fresh)fresh.innerHTML=products.slice(-3).map(p=>`<a href="product.html?id=${p.id}" class="lux-new-card">${sprite(p)}<b>${p.name}</b><small>${p.category}</small><strong>${money(p.price)}</strong></a>`).join('');
  const best=$('#bestSellerAdmin');if(best)best.innerHTML=products.slice(2,7).map(p=>`<a href="product.html?id=${p.id}" title="${p.name}">${sprite(p,'lux-best-img')}</a>`).join('');
  const trend=$('#trendingAdmin');if(trend){const p=products.find(x=>x.id===12)||products[0];trend.innerHTML=p?`<div class="lux-alert-item">${sprite(p,'lux-alert-img')}<div><b>${p.name}</b><small>High demand</small></div><a href="product.html?id=${p.id}">View</a></div>`:''}
}
function renderLowStock(){const root=$('#lowStockList');if(!root)return;const low=products.filter(p=>Number(p.stock||0)<=12).slice(0,3);root.innerHTML=low.length?low.map(p=>`<div class="lux-alert-item">${sprite(p,'lux-alert-img')}<div><b>${p.name}</b><small>Only ${p.stock} left in stock</small></div><button onclick="editP(${p.id})">Restock</button></div>`).join(''):'<p class="muted">All products have healthy stock.</p>'}
async function load(){
  try{products=await api('/api/products');renderVisuals();sProducts.textContent=products.length;sStock.textContent=products.reduce((s,p)=>s+Number(p.stock||0),0)}catch(e){adminStatus.textContent='Catalogue unavailable: '+e.message}
  try{const me=await api('/api/me');if(!me.user||me.user.role!=='admin'){adminStatus.innerHTML='Store preview is live. <b>Admin login required</b> for inventory and order management. Use <a href="admin_setup.html">Admin Setup</a> or <a href="account.html">My Account</a>.';sOrders.textContent='—';sRevenue.textContent='—';renderLowStock();return}adminStatus.textContent=`Admin: ${me.user.name} • ${me.user.email}`;products=await api('/api/admin/products');orders=await api('/api/admin/orders');renderVisuals();renderLowStock();renderProducts();renderOrders();sProducts.textContent=products.length;sStock.textContent=products.reduce((s,p)=>s+Number(p.stock||0),0);sOrders.textContent=orders.length;sRevenue.textContent=money(orders.filter(o=>o.payment_status==='paid'||o.payment_method==='Cash on Delivery').reduce((s,o)=>s+Number(o.total),0))}catch(e){adminStatus.textContent=e.message;renderLowStock()}
}
function renderProducts(){const root=$('#productRows');if(!root)return;root.innerHTML=products.map(p=>`<tr><td><div class="lux-table-product">${sprite(p,'lux-table-img')}<b>${p.name}</b></div></td><td>${p.category}</td><td>${money(p.price)}</td><td><span class="${Number(p.stock)<10?'lux-stock low':'lux-stock'}">${p.stock}</span></td><td>${p.active?'Active':'Hidden'}</td><td class="admin-actions"><button onclick="editP(${p.id})">Edit</button><button onclick="toggleP(${p.id})">${p.active?'Hide':'Show'}</button><button onclick="delP(${p.id})">Delete</button></td></tr>`).join('')}
function renderOrders(){const root=$('#orderRows');if(!root)return;const statuses=['Payment pending','Order confirmed','Processing','Packed','Shipped','Delivered','Cancelled'];root.innerHTML=orders.length?orders.slice(0,30).map(o=>`<div class="lux-order-card"><div><b>${o.order_no}</b><small>${o.customer_name} • ${o.customer_email}</small><div class="tracking-edit"><input id="courier-${o.id}" placeholder="Courier" value="${o.shipping_courier||''}"><input id="track-${o.id}" placeholder="Tracking number" value="${o.tracking_number||''}"><input id="url-${o.id}" placeholder="Tracking URL" value="${o.tracking_url||''}"></div></div><strong>${money(o.total)}</strong><select id="status-${o.id}">${statuses.map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select><button onclick="saveOrder(${o.id})">Save</button></div>`).join(''):'<p class="muted">No database orders yet.</p>'}
async function saveOrder(id){const status=$('#status-'+id).value,shipping_courier=$('#courier-'+id).value.trim(),tracking_number=$('#track-'+id).value.trim(),tracking_url=$('#url-'+id).value.trim();try{await api('/api/admin/orders/'+id,{method:'PUT',body:JSON.stringify({status,shipping_courier,tracking_number,tracking_url})});await load()}catch(x){alert(x.message)}}
const form=$('#addProduct');if(form)form.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));['price','mrp','stock'].forEach(k=>d[k]=Number(d[k]));try{await api('/api/admin/products',{method:'POST',body:JSON.stringify(d)});e.target.reset();load()}catch(x){alert(x.message)}};
async function editP(id){const p=products.find(x=>x.id===id);if(!p)return;const name=prompt('Product name',p.name);if(name===null)return;const price=Number(prompt('Price',p.price)),stock=Number(prompt('Stock',p.stock));if(!Number.isFinite(price)||!Number.isFinite(stock))return;try{await api('/api/admin/products/'+id,{method:'PUT',body:JSON.stringify({...p,name,price,stock})});load()}catch(x){alert(x.message)}}
async function toggleP(id){const p=products.find(x=>x.id===id);try{await api('/api/admin/products/'+id,{method:'PUT',body:JSON.stringify({...p,active:!p.active})});load()}catch(x){alert(x.message)}}
async function delP(id){if(!confirm('Delete this product from the database?'))return;try{await api('/api/admin/products/'+id,{method:'DELETE'});load()}catch(x){alert(x.message)}}
load();
